#!/bin/sh -e

# Automatically added by dh_installinit/11.3.2
if [ "$1" = "purge" ] ; then
	update-rc.d mouseemu remove >/dev/null
fi


# In case this system is running systemd, we make systemd reload the unit files
# to pick up changes.
if [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section


# remove symlink in /etc/udev/rules.d 
if [ "$1" = "purge" ]; then
    rm -f /etc/udev/rules.d/025_mouseemu.rules
    if [ -x /sbin/udevcontrol ] ; then
        # udevcontrol fails if udev is not running, but installation should not abort
        udevcontrol reload_rules || true
    fi
fi

